In [2]:
[[123,12,123,12,33],[], []]

[[123, 12, 123, 12, 33], [], []]

In [3]:
import numpy
n = numpy.arange(27)

In [5]:
# Numpy array
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
type(n)

numpy.ndarray

In [10]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
# Convert array to numpy array. Note that is is a ragged.
m = numpy.asarray([[123,12,123,12,33],[], []], dtype=object)
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)